name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs at 00:00 every day
  push:
    branches:
      - main  # You can change this to your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate snake animation
        uses: Platane/snk@v2
        with:
          github_user_name: imran-imtiaz48
          outputs: dist/snake.svg

      - name: Add & Commit
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add -A
          git commit -m 'Generate snake animation'

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
